export default [{
    name: 'AutoRepair&Services',
    mobile: '9891123455',
    landline: '0111235689',
    add: '11/1 Mayur Vihar New delhi',
    email: 'autorepair&services@gmail.com',
    employees: [{
        name: 'Avinash Kumar',
        add: '907, plot 2, sector 11 Noida',
        mobile: '9919234512',
        joiningDate: '2022-04-20',
        email: 'avinashtest@gmail.com',
        salary: '45000',
        designation: 'Supervisor',
        supervisorEmail: 'N/A',
    }, {
        name: 'Ram Chandran',
        add: '907, plot 2, sector 11 Noida',
        mobile: '9919234512',
        joiningDate: '2022-04-20',
        email: 'ramchandran@gmail.com',
        designation: 'Mechanic-Washing',
        salary: '15000',
        supervisorEmail: 'avinashtest@gmail.com',
    }, {
        name: 'Mahesh Muni',
        add: '20th Main BTM Layout Bangalore',
        mobile: '9919234512',
        joiningDate: '2022-04-21',
        designation: 'Mechanic-Repair',
        email: 'maheshmuni@gmail.com',
        salary: '17000',
        supervisorEmail: 'avinashtest@gmail.com',
    }, {
        name: 'Jayesh kanitkar',
        add: 'No 10, plot no. 11,  Panvel, Mumbai',
        mobile: '9967234523',
        joiningDate: '2022-04-22',
        designation: 'Mechanic-Service',
        email: 'Jayeshkanitkar@gmail.com',
        salary: '19000',
        supervisorEmail: 'avinashtest@gmail.com',
    }]
}, {
    name: 'AutoRepair&Services',
    mobile: '9810123455',
    landline: '0801235689',
    add: '2nd Main BTM Layout, Bangalore',
    email: 'autorepair&services@gmail.com',
    employees: [{
        name: 'Avinash VM',
        add: '907, plot 3, sector 11 Noida',
        mobile: '9919234512',
        joiningDate: '2022-04-20',
        designation: 'Supervisor',
        email: 'avinashtest1@gmail.com',
        salary: '45000',
        supervisorEmail: 'N/A',
    }, {
        name: 'Mahesh Muni',
        add: '20th Main BTM Layout Bangalore',
        mobile: '9919234512',
        joiningDate: '2022-04-21',
        designation: 'Mechanic-Repair',
        email: 'maheshmuni@gmail.com',
        salary: '17000',
        supervisorEmail: 'avinashtest1@gmail.com',
    }, {
        name: 'Jayesh kanitkar',
        add: 'No 10, plot no. 11,  Panvel, Mumbai',
        mobile: '9967234523',
        joiningDate: '2022-04-22',
        designation: 'Mechanic-Washing',
        email: 'Jayeshkanitkar@gmail.com',
        salary: '19000',
        supervisorEmail: 'avinashtest1@gmail.com',
    }]
}, {
    name: 'AutoRepair&Services',
    mobile: '9867123455',
    landline: '0221235689',
    add: 'No 8, Akash ganga Building, Panvel, Mumbai',
    email: 'autorepair&services@gmail.com',
    employees: []
}]
